### ISSUE TITLE
502 Bad Gateway on main site https://www.codegrepper.com

### ISSUE THREAD

**Issue by Edsonjorgef1** [jareer12/Code-Grepper#1]
The site is currently displaying this error:  **502 Bad Gateway** nginx/1.15.5 (Ubuntu)

https://www.codegrepper.com/

**Comment by jub0t** [comment]
Hey there just wanted to inform you we [@Code-Grepper](https://github.com/Code-Grepper) are not the official GitHub organization for Codegrepper. Also, the website usually goes offline for reasons we don't know. The error "**502 Bad Gateway** Nginx/1.15.5 (Ubuntu)" usually appears. The best thing you can do is wait for it to be fixed,

You can find the official organization [here](https://github.com/codegrepper).
