### ISSUE TITLE
get_answers 404

### ISSUE THREAD

**Issue by jiito** [jareer12/Code-Grepper#2]
This API is great! 

It seems that get_answers in returning with a 404. After a little investigation, it seems that the pages are now being statically loaded.

Seems like `docs/answers/GETANSWERS.MD` should be updated.

**Comment by jub0t** [comment]
You need to provide an API version using the `v` param. 
```
https://www.codegrepper.com/api/get_answers_1.php?v=3
```

Ex:
```
https://www.codegrepper.com/api/get_answers_1.php?v=3&s=loop
```
