### ISSUE TITLE
Where can one find his/her userID

### ISSUE THREAD

**Issue by AnatuGreen** [jareer12/Code-Grepper#4]
I have checked Codegrepper, my account sections and there is no userID specified. Only user slug and attempting to access my information through fetch request does not work. Error keeps returning

**Comment by jub0t** [comment]
> I have checked Codegrepper, my account sections and there is no userID specified. Only user slug and attempting to access my information through fetch request does not work. Error keeps returning

You can use the search api https://www.codegrepper.com/api/autocomplete_users_search.php - https://github.com/Code-Grepper/Code-Grepper-API-Documentation/blob/main/docs/teams/INVITEUSER.MD To get user's info & id by username. 

Or get your userId from the dev console. Goto your codegrepper.com profile page press F12 and refresh. Check fetch/xhr tab and get your userId from there.
